# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import proto.admin_invite_pb2 as admin__invite__pb2

GRPC_GENERATED_VERSION = "1.67.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in admin_invite_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class AdminInviteServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
            "/admin_invite.AdminInviteService/Create",
            request_serializer=admin__invite__pb2.CreateRequest.SerializeToString,
            response_deserializer=admin__invite__pb2.CreateResponse.FromString,
            _registered_method=True,
        )
        self.Get = channel.unary_unary(
            "/admin_invite.AdminInviteService/Get",
            request_serializer=admin__invite__pb2.GetRequest.SerializeToString,
            response_deserializer=admin__invite__pb2.GetResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/admin_invite.AdminInviteService/Delete",
            request_serializer=admin__invite__pb2.DeleteRequest.SerializeToString,
            response_deserializer=admin__invite__pb2.DeleteResponse.FromString,
            _registered_method=True,
        )
        self.List = channel.unary_stream(
            "/admin_invite.AdminInviteService/List",
            request_serializer=admin__invite__pb2.ListRequest.SerializeToString,
            response_deserializer=admin__invite__pb2.AdminInvite.FromString,
            _registered_method=True,
        )


class AdminInviteServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AdminInviteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Create": grpc.unary_unary_rpc_method_handler(
            servicer.Create,
            request_deserializer=admin__invite__pb2.CreateRequest.FromString,
            response_serializer=admin__invite__pb2.CreateResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=admin__invite__pb2.GetRequest.FromString,
            response_serializer=admin__invite__pb2.GetResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=admin__invite__pb2.DeleteRequest.FromString,
            response_serializer=admin__invite__pb2.DeleteResponse.SerializeToString,
        ),
        "List": grpc.unary_stream_rpc_method_handler(
            servicer.List,
            request_deserializer=admin__invite__pb2.ListRequest.FromString,
            response_serializer=admin__invite__pb2.AdminInvite.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "admin_invite.AdminInviteService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "admin_invite.AdminInviteService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class AdminInviteService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin_invite.AdminInviteService/Create",
            admin__invite__pb2.CreateRequest.SerializeToString,
            admin__invite__pb2.CreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin_invite.AdminInviteService/Get",
            admin__invite__pb2.GetRequest.SerializeToString,
            admin__invite__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin_invite.AdminInviteService/Delete",
            admin__invite__pb2.DeleteRequest.SerializeToString,
            admin__invite__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/admin_invite.AdminInviteService/List",
            admin__invite__pb2.ListRequest.SerializeToString,
            admin__invite__pb2.AdminInvite.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
