metrics:
  wal_directory: /tmp/agent/wal
  global:
    scrape_interval: 15s
  configs:
    - name: default
      scrape_configs:
        - job_name: platform-service
          static_configs:
            - targets: ['platform-service:8000']
              labels:
                job: platform-service
        - job_name: admin-service
          static_configs:
            - targets: ['admin-service:8001']
              labels:
                job: admin-service
        - job_name: admin-invite-service
          static_configs:
            - targets: ['admin-invite-service:8002']
              labels:
                job: admin-invite-service
        - job_name: user-service
          static_configs:
            - targets: ['user-service:8003']
              labels:
                job: user-service

      remote_write:
        - url: http://mimir:9090/api/v1/push

logs:
  configs:
    - name: default
      clients:
        - url: http://loki:3100/loki/api/v1/push
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: platform-service-logs
          static_configs:
            - targets: ['localhost']
              labels:
                job: platform-service
                __path__: /var/log/platform-service/platform-service.log
        - job_name: admin-service-logs
          static_configs:
            - targets: ['localhost']
              labels:
                job: admin-service
                __path__: /var/log/admin-service/admin-service.log
        - job_name: admin-invite-service-logs
          static_configs:
            - targets: ['localhost']
              labels:
                job: admin-invite-service
                __path__: /var/log/admin-invite-service/admin-invite-service.log
        - job_name: user-service-logs
          static_configs:
            - targets: ['localhost']
              labels:
                job: user-service
                __path__: /var/log/user-service/user-service.log
