# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

import proto.user_pb2 as user__pb2

GRPC_GENERATED_VERSION = "1.67.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in user_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class UserServiceStub(object):
    """AdminService defines the gRPC service for managing administrator accounts.
    It includes methods for registration, login, retrieval, and updates of admin details.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            "/admin.UserService/Register",
            request_serializer=user__pb2.RegisterRequest.SerializeToString,
            response_deserializer=user__pb2.RegisterResponse.FromString,
            _registered_method=True,
        )
        self.Login = channel.unary_unary(
            "/admin.UserService/Login",
            request_serializer=user__pb2.LoginRequest.SerializeToString,
            response_deserializer=user__pb2.LoginResponse.FromString,
            _registered_method=True,
        )
        self.Get = channel.unary_unary(
            "/admin.UserService/Get",
            request_serializer=user__pb2.GetRequest.SerializeToString,
            response_deserializer=user__pb2.GetResponse.FromString,
            _registered_method=True,
        )
        self.Update = channel.unary_unary(
            "/admin.UserService/Update",
            request_serializer=user__pb2.UpdateRequest.SerializeToString,
            response_deserializer=user__pb2.UpdateResponse.FromString,
            _registered_method=True,
        )
        self.List = channel.unary_stream(
            "/admin.UserService/List",
            request_serializer=user__pb2.ListRequest.SerializeToString,
            response_deserializer=user__pb2.User.FromString,
            _registered_method=True,
        )


class UserServiceServicer(object):
    """AdminService defines the gRPC service for managing administrator accounts.
    It includes methods for registration, login, retrieval, and updates of admin details.
    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=user__pb2.RegisterRequest.FromString,
            response_serializer=user__pb2.RegisterResponse.SerializeToString,
        ),
        "Login": grpc.unary_unary_rpc_method_handler(
            servicer.Login,
            request_deserializer=user__pb2.LoginRequest.FromString,
            response_serializer=user__pb2.LoginResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=user__pb2.GetRequest.FromString,
            response_serializer=user__pb2.GetResponse.SerializeToString,
        ),
        "Update": grpc.unary_unary_rpc_method_handler(
            servicer.Update,
            request_deserializer=user__pb2.UpdateRequest.FromString,
            response_serializer=user__pb2.UpdateResponse.SerializeToString,
        ),
        "List": grpc.unary_stream_rpc_method_handler(
            servicer.List,
            request_deserializer=user__pb2.ListRequest.FromString,
            response_serializer=user__pb2.User.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "admin.UserService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("admin.UserService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class UserService(object):
    """AdminService defines the gRPC service for managing administrator accounts.
    It includes methods for registration, login, retrieval, and updates of admin details.
    """

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.UserService/Register",
            user__pb2.RegisterRequest.SerializeToString,
            user__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.UserService/Login",
            user__pb2.LoginRequest.SerializeToString,
            user__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.UserService/Get",
            user__pb2.GetRequest.SerializeToString,
            user__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Update(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/admin.UserService/Update",
            user__pb2.UpdateRequest.SerializeToString,
            user__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/admin.UserService/List",
            user__pb2.ListRequest.SerializeToString,
            user__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
